import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { AppConfigurationService } from '../app-configuration.service';
import { IAppConfiguration } from '../iapp-configuration';
import { BaseDetailsComponent, Globals, PickerDialogService, ErrorService } from 'src/app/common/shared';
import { GlobalPermissionService } from 'src/app/core/global-permission.service';

@Component({
  selector: 'app-app-configuration-details',
  templateUrl: './app-configuration-details.component.html',
  styleUrls: ['./app-configuration-details.component.scss'],
})
export class AppConfigurationDetailsComponent extends BaseDetailsComponent<IAppConfiguration> implements OnInit {
  title = 'AppConfiguration';
  parentUrl = 'appconfiguration';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public global: Globals,
    public appConfigurationService: AppConfigurationService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, global, pickerDialogService, appConfigurationService, errorService);
  }

  ngOnInit() {
    this.entityName = 'AppConfiguration';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      id: [{ value: '', disabled: true }, Validators.required],
      type: ['', Validators.required],
      value: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'type',
        label: 'type',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },

      {
        name: 'value',
        label: 'value',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
    ];
  }

  onItemFetched(item: IAppConfiguration) {
    this.item = item;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let appConfiguration = this.itemForm.getRawValue();
    super.onSubmit(appConfiguration);
  }
}
